### ISSUE TITLE
Custom texturepacks compatibility

### ISSUE THREAD

**Issue by Kubimate** [BTW-Community/BTWMapMarkers#6]
No markers visible on map when using custom texturepack.
Mod uses and overwrites the same texture file as base game for marker textures, which is then overwriten by texturepacks. Texturepacks must have compatible file for this mod to be usable.

_Suggestion:
Better solution would be to use separate marker texture file for mod markers only, and then let texturepacks overwrite this file, or leave it as mods default, if possible._

**Comment by psychosledge** [comment]
Fixed in next release
